### ISSUE TITLE
IDAStopTest2 bug

### ISSUE THREAD

**Issue by jehelset** [LLNL/sundials#339] opened 2023-09-15 00:40 UTC
bfec386d9 moved check for tn past tstop before check for tn past tout in IDAStopTest2:
 https://github.com/LLNL/sundials/commit/bfec386d94218dd27e85ceb8798a9021a83690ef?diff=split#diff-a624e4aaf10771efab2a0c451839e9c4f24613e0f5ee296e82cf5f5bc4fcecebL2101

in a test i have a simple linear system dxdt = 1.0, and root function g(x) = 1.0 - x, doing fixed-step integration with dt = 0.1, and tstop = 1.5, at t = 0.7, instead of IDAStep computing the solution t = 0.8, like it does in version `6.6.0`, it now, in `6.6.1`, instead does an early return and reports stop!

**Comment by gardner48** [comment] 2023-09-15 01:04
@jehelset thanks for reporting this issue. The change you point to, while fixing a different minor bug, did introduce a new bug that will cause an unintended return at `tstop` when rather than at `tout`.  I'll propose a fix for this regression shortly.

**Comment by jehelset** [comment] 2023-09-15 10:22
yes, it is a nice change otherwise. thanks!

**Comment by balos1** [comment] 2023-10-04 19:29
Fixed by #349.

**Closed by balos1** 2023-10-04 19:29 UTC
Labels: bug, pkg-IDA
