### ISSUE TITLE
Floating-point underflow in root-finding functions

### ISSUE THREAD

**Issue by UnkindPartition** [LLNL/sundials#57] opened 2020-12-29 16:08 UTC
Root-finding functions like `arkRootfind` and `cvRootfind` use floating-point multiplication to check whether a sign change has occurred. This is prone to floating-point underflow (e.g. `(-1e-166) * 1e-166` evaluates to 0) which makes the algorithm assume that the sign change was on the wrong sub-interval.

[Here's a commit](https://github.com/novadiscovery/sundials/commit/f7a725e9964a4177b6055a972ff25fea48c404f0) fixing this issue for cvode and arkode; feel free to pull it into sundials if you find it useful. The fix may need to be ported to other packages as well.

Thanks for maintaining sundials!

**Comment by eltix** [comment] 2022-11-25 09:46
@balos1 Any chance this can be merged upstream? Do you want us to open a PR?

Thanks for maintaining Sundials :)

**Closed** 2022-12-07 19:52 UTC
Labels: enhancement

**Comment by guibou** [comment] 2026-06-15 12:22
I wanted to add a note on this issue. I'm working on something related to root finding and hit a problem with the current implementation.

@UnkindPartition said that `(-1e-166) * 1e-166` evaluates to `0` and is correct. However, the problem is not really that the value is `0`, the problem is that the test for sign, `a < ZERO` is incomplete, it should actually be something like `a < ZERO || isNegativeZero (a)`, which could be implemented using for example `copysign`.

The current change (e.g. instead of testing `a * b < ZERO`, we test `( ( (a) < 0 && (b) > 0 ) || ( (a) > 0 && (b) < 0 ) )` could actually be wrong again if the individual root computation underflow to zero, leading to both `a` and `b` to be "positive" even if they were supposed to be considered as negative.

For example, in my solver, I do have a root function which is like `c * d` where both `c` and `d` can be really small. I can unfortunately miss root (or got them triggered too quickly) when `c * d` cancels out to `0`.

I actually need to rewrite my root differently. But unfortunately, these root are provided by external user and I can only try to do a static analysis of the function they provide and rewrite them for numerical accuracy.

Would you consider a merge request replacing the current `( ( (a) < 0 && (b) > 0 ) || ( (a) > 0 && (b) < 0 ) )` by something like `copysign(1, a) * copysign(1, b) < 0`?

**Comment by guibou** [comment] 2026-06-15 12:22
@balos1 @eltix ping ;)
